rootProject.name = 'kv-store'

include 'core'
include 'io'
include 'indexing'
include 'cache'
include 'wal'
include 'memtable'
include 'sstable'
include 'compaction'
include 'concurrency'
include 'telemetry'
include 'tools'
include 'engine'
include 'api'
include 'integration-tests'
include 'benchmarks'
